### ISSUE TITLE
gitlabform ignores -k option

### ISSUE THREAD

**Issue by pijoter** [egnyte/gitlabform#133]
we have gitlab installed on private network (without internet access)
gitlabform -h hangs, gitlabform -k -h also hangs and timeouts

gitlabform-1.18.0

```
Traceback (most recent call last):
  File "/usr/bin/gitlabform", line 6, in <module>
    GitLabForm().main()
  File "/usr/lib/python3.6/site-packages/gitlabform/gitlabform/core.py", line 41, in __init__
    ) = self.parse_args()
  File "/usr/lib/python3.6/site-packages/gitlabform/gitlabform/core.py", line 105, in parse_args
    "-V", "--version", action="version", version=self.get_version(False)
  File "/usr/lib/python3.6/site-packages/gitlabform/gitlabform/core.py", line 152, in get_version
    latest_version = luddite.get_version_pypi("gitlabform")
  File "/usr/lib/python3.6/site-packages/luddite.py", line 105, in get_version_pypi
    latest = get_data_pypi(name, index)["info"]["version"]
  File "/usr/lib/python3.6/site-packages/luddite.py", line 94, in get_data_pypi
    data = json_get(uri)
  File "/usr/lib/python3.6/site-packages/luddite.py", line 79, in json_get
    response = urlopen(request)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 13] Permission denied>
```

**Comment by gdubicki** [comment]
Thanks for using GitLabForm and reporting the issue, @pijoter ! I have fixed it and released 1.18.1 with the fix today. Please reopen if you still observe the issue after updating.
