### ISSUE TITLE
Removed approvers endpoint used by GitLabForm

### ISSUE THREAD

**Issue by sgraca** [egnyte/gitlabform#220]
**Describe the bug**

In GitLab [13.11.0](https://gitlab.com/gitlab-org/gitlab/-/blob/master/CHANGELOG-EE.md#13110-2021-04-22) a deprecated project approvers update REST API has been removed. This endpoint is still invoked by GitLabForm to delete legacy approvers (see [merge_request_processor.py](https://github.com/egnyte/gitlabform/blob/main/gitlabform/gitlabform/processors/project/merge_requests_processor.py#L42)) if the response from GitLab contains `approvers` or `approver_groups`. Unfortunately although the endpoint has been removed above attributes are still returned by GitLab making GitLabForm call non-existent endpoint.

```
Traceback (most recent call last):
  File "/gitlabform/gitlabform/gitlabform/core.py", line 315, in process_all
    self.project_processors.process_project(
  File "/gitlabform/gitlabform/gitlabform/processors/project/__init__.py", line 57, in process_project
    processor.process(project_and_group, configuration, dry_run)
  File "/gitlabform/gitlabform/gitlabform/processors/util/decorators.py", line 42, in method_wrapper
    return method(self, project_and_group, SafeDict(configuration), dry_run)
  File "/gitlabform/gitlabform/gitlabform/processors/abstract_processor.py", line 34, in process
    self._process_configuration(project_or_project_and_group, configuration)
  File "/gitlabform/gitlabform/gitlabform/processors/project/merge_requests_processor.py", line 37, in _process_configuration
    self.gitlab.delete_legacy_approvers(project_and_group)
  File "/gitlabform/gitlabform/gitlab/projects.py", line 235, in delete_legacy_approvers
    self._make_requests_to_api(
  File "/gitlabform/gitlabform/gitlab/core.py", line 137, in _make_requests_to_api
    response = self._make_request_to_api(
  File "/gitlabform/gitlabform/gitlab/core.py", line 220, in _make_request_to_api
    raise NotFoundException("Resource path='%s' not found!" % url)
gitlabform.gitlab.core.NotFoundException: Resource path='****edited****/api/v4/projects/****edited****/approvers' not found!
```

Here's the response from `projects/:id/approvals`
```
{
  "approvers": [],
  "approver_groups": [],
  "approvals_before_merge": 1,
  "reset_approvals_on_push": true,
  "disable_overriding_approvers_per_merge_request": true,
  "merge_requests_author_approval": false,
  "merge_requests_disable_committers_approval": true,
  "require_password_to_approve": false
}
```

We're using an older version of GitLabForm but the same logic triggering the issue is still on the main branch.

**GitLabForm version**

GitLabForm version: 1.18.3.2 (the latest is 2.0.0.post1 - please update!)

**Comment by Pigueiras** [comment]
We are also hitting this :(, do you want to delete that part of the code or do you want to implement some kind of logic with if gitlab_version < 13.11, execute `delete_legacy_approvers`? @gdubicki
