### ISSUE TITLE
Push rule diff fails on unknown original value

### ISSUE THREAD

**Issue by seboudry** [egnyte/gitlabform#223]
On some projects, dry-run push rules fails.
The error came from `???` value but don't know why original value can't be retrieve on some projects.

```
GitLabForm version: 2.0.0.post1 
```

```
config_version: 2

projects_and_groups:

  "my-group/*":
    project_push_rules:
      commit_committer_check: true
      member_check: true
```

On some projects, I got this error:
```
Processing project_push_rules in dry-run mode.
Warning: Error occurred while processing project my-group/my-project, exception:
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/gitlabform/gitlabform/gitlabform/core.py", line 548, in process_all
    self.project_processors.process_project(
  File "/gitlabform/gitlabform/gitlabform/processors/project/__init__.py", line 63, in process_project
    processor.process(project_and_group, configuration, dry_run, output_file)
  File "/gitlabform/gitlabform/gitlabform/processors/util/decorators.py", line 42, in method_wrapper
    return method(self, project_and_group, SafeDict(configuration), *args)
  File "/gitlabform/gitlabform/gitlabform/processors/abstract_processor.py", line 41, in process
    self._print_diff(
  File "/gitlabform/gitlabform/gitlabform/processors/project/project_push_rules_processor.py", line 32, in _print_diff
    DifferenceLogger.log_diff(
  File "/gitlabform/gitlabform/gitlabform/processors/util/difference_logger.py", line 21, in log_diff
    changes = [
  File "/gitlabform/gitlabform/gitlabform/processors/util/difference_logger.py", line 22, in <listcomp>
    [k, json.dumps(current_config.get(k, "???")), json.dumps(v)]
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by gdubicki** [comment]
Thanks for reporting this!

It should be fixed in v2.0.3 which has just been released. Please reopen if you are still seeing this after updating GitLabForm.
