### ISSUE TITLE
GitLab throws 404 when you try to share a group A with a group B if LDAP group links are enabled for group A

### ISSUE THREAD

**Issue by gdubicki** [egnyte/gitlabform#302]
**Describe the bug**

We have a group A that has been shared using LDAP group links with some users. When you try to switch this group to be shared with other groups, including B, then you get a misleading HTTP 404:

```
Processing section 'group_shared_with'
Warning: Error occurred while processing group devops, exception:

Resource with url='https://gitlab.example.com/api/v4/groups/408/share' not found (HTTP 404)!

Traceback (most recent call last):
  File "/Users/gdubicki/git/gitlabform/gitlabform/core.py", line 361, in run
    self.group_processors.process_entity(
  File "/Users/gdubicki/git/gitlabform/gitlabform/processors/__init__.py", line 30, in process_entity
    processor.process(
  File "/Users/gdubicki/git/gitlabform/gitlabform/processors/util/decorators.py", line 42, in method_wrapper
    return method(self, project_and_group, SafeDict(configuration), *args)
  File "/Users/gdubicki/git/gitlabform/gitlabform/processors/abstract_processor.py", line 48, in process
    self._process_configuration(project_or_project_and_group, configuration)
  File "/Users/gdubicki/git/gitlabform/gitlabform/processors/group/group_shared_with_processor.py", line 77, in _process_configuration
    self.gitlab.add_share_to_group(
  File "/Users/gdubicki/git/gitlabform/gitlabform/gitlab/groups.py", line 181, in add_share_to_group
    return self._make_requests_to_api(
  File "/Users/gdubicki/git/gitlabform/gitlabform/gitlab/core.py", line 129, in _make_requests_to_api
    response = self._make_request_to_api(
  File "/Users/gdubicki/git/gitlabform/gitlabform/gitlab/core.py", line 220, in _make_request_to_api
    raise NotFoundException(
gitlabform.gitlab.core.NotFoundException: Resource with url='https://gitlab.example.com/api/v4/groups/408/share' not found (HTTP 404)!
```

A quick workaround it to disable the LDAP group links manually and then re-run GitLabForm.

**GitLabForm version**

🏗  GitLabForm version: 2.7.1 = the latest stable 😊

**GitLab version**

(can't disclose)

**Comment by amimas** [comment]
This issue was based on GitLabForm v2.7.1 where `group_share_with` configuration was used. That configuration has been [dropped in v3 release](https://gitlabform.github.io/gitlabform/changelog/#300). Latest version of GitLabForm currently is v5. Closing this issue for now. Please open a new issue with sample config if similar issue still persists.
