### ISSUE TITLE
KeyError: 'x-total-pages'

### ISSUE THREAD

**Issue by idetoile** [egnyte/gitlabform#37]
Hello,
first thank you for this great tool,

I got this error:
Connected to GitLab version: 11.9.4-ee (55be7f0)
Config file is declared to be compatible with GitLab API v4
Reading config from: .../config.yml
>>> Processing ALL groups and and projects
Traceback (most recent call last):
  File "/home/jo/.local/bin/gitlabform", line 6, in <module>
    GitLabForm().main()
  File "/home/jo/.local/lib/python3.6/site-packages/gitlabform/gitlabform/core.py", line 135, in main
    projects_and_groups = self.get_projects_list()
  File "/home/jo/.local/lib/python3.6/site-packages/gitlabform/gitlabform/core.py", line 146, in get_projects_list
    groups = self.gl.get_groups()
  File "/home/jo/.local/lib/python3.6/site-packages/gitlabform/gitlab/groups.py", line 10, in get_groups
    result = self._make_requests_to_api("groups?all_available=true", paginated=True)
  File "/home/jo/.local/lib/python3.6/site-packages/gitlabform/gitlab/core.py", line 98, in _make_requests_to_api
    total_pages = int(first_response.headers['X-Total-Pages'])
  File "/home/jo/.local/lib/python3.6/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-total-pages'

**Comment by gdubicki** [comment]
Hi @idetoile !

Unfortunately I don't have this version of GitLab to reproduce it, but I think that automating using pagination for requests to GitLab should solve it.

Can you please check out code from this branch https://github.com/egnyte/gitlabform/tree/automate_using_pagination and try using it?

**Comment by gdubicki** [comment]
Closing because of lack of activity. Please reopen if neede, @idetoile .
