### ISSUE TITLE
1.8.0 version issues

### ISSUE THREAD

**Issue by weakcamel** [egnyte/gitlabform#64]
Hello,
I've tried upgrading from v1.6.0 to 1.8.0 and encountered problems with it.

Stack trace:

```
*** # of groups to process: 39
*** # of projects to process: 238
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/config-Z17lvQEG/bin/gitlabform", line 6, in <module>
    GitLabForm().main()
  File "/root/.local/share/virtualenvs/config-Z17lvQEG/lib/python3.7/site-packages/gitlabform/gitlabform/core.py", line 135, in main
    self.process_all(projects_and_groups, groups)
  File "/root/.local/share/virtualenvs/config-Z17lvQEG/lib/python3.7/site-packages/gitlabform/gitlabform/core.py", line 197, in process_all
    configuration = self.c.get_effective_config_for_group(group)
  File "/root/.local/share/virtualenvs/config-Z17lvQEG/lib/python3.7/site-packages/gitlabform/configuration/projects_and_groups.py", line 111, in get_effective_config_for_group
    group_config = self.get_config_for_group(group)
AttributeError: 'Configuration' object has no attribute 'get_config_for_group'
```

**Comment by gdubicki** [comment]
Oups, sorry! It should be fixed in v 1.8.1 release a moment ago.

**Comment by gdubicki** [comment]
Please reopen this ticket if you still have issues, @weakcamel .

**Comment by weakcamel** [comment]
Sorry for delay, I've been out of the computerized world for the last wek ;-)

Yes, 1.8.1 works like a charm, many thanks!
