### ISSUE TITLE
Errors when repo contains periods

### ISSUE THREAD

**Issue by masonbivens** [egnyte/gitlabform#67]
Original Name
```
* [27/218] Processing: foobar-ltd/technology/infra/ans/legacy.ksops.terraform
+++ Error while processing 'foobar-ltd/technology/infra/ans/legacy.ksops.terraform'
Traceback (most recent call last):
  File "/gitlabform/gitlabform/gitlabform/core.py", line 220, in process_all
    self.process_project_push_rules(project_and_group, configuration)
  File "/gitlabform/gitlabform/gitlabform/core.py", line 31, in method_wrapper
    return method(self, project_and_group, configuration)
  File "/gitlabform/gitlabform/gitlabform/core.py", line 248, in process_project_push_rules
    self.gl.put_project_push_rules(project_and_group, push_rules)
  File "/gitlabform/gitlabform/gitlab/projects.py", line 90, in put_project_push_rules
    self._make_requests_to_api("projects/%s/push_rule", project_and_group_name, 'PUT', push_rules)
  File "/gitlabform/gitlabform/gitlab/core.py", line 83, in _make_requests_to_api
    response = self._make_request_to_api(path_as_format_string, args, method, data, expected_codes, json)
  File "/gitlabform/gitlabform/gitlab/core.py", line 116, in _make_request_to_api
    raise NotFoundException("Resource path='%s' not found!" % url)
gitlabform.gitlab.core.NotFoundException: Resource path='https://gitlab.com/api/v4/projects/foobar-ltd%2Ftechnology%2Finfra%2Fans%2Flegacy.ksops.terraform/push_rule' not found!
```

After removing `.` from the name
```
* [8/13] Processing: foobar-ltd/technology/infra/ans/legacy-ksops-base
* [9/13] Processing: foobar-ltd/technology/infra/ans/legacy-ksops-credentials
* [10/13] Processing: foobar-ltd/technology/infra/ans/legacy-ksops-iamfit
* [11/13] Processing: foobar-ltd/technology/infra/ans/legacy-ksops-iamsplunk
* [12/13] Processing: foobar-ltd/technology/infra/ans/legacy-ksops-puppetmaster
* [13/13] Processing: foobar-ltd/technology/infra/ans/legacy-ksops-terraform

➜ gitlab-config
```

**Comment by gdubicki** [comment]
This is a bug in GitLab API. A simple workaround is to use project_id in its case instead of project name. This workaround will be included in the next gitlabform version.
