### ISSUE TITLE
Problem with push_rules

### ISSUE THREAD

**Issue by grzesuav** [egnyte/gitlabform#85]
I have set setting for whole group. 
For some project in the group settings are correctly applied, for some others I see error :
```
2020-02-25 14:13:34.183 | - | - | app-1582639980-gjzfc | Setting project push rules: {'author_email_regex': '', 'branch_name_regex': '', 'commit_message_regex': '^((Revert .+)\|(Add renovate.json)\|(Merge branch .+)\|(build\|ci\|chore\|docs\|feat\|bugfix\|fix\|perf\|refactor\|revert\|style\|test)(\\(.+\\))?:( #\\d+ -)? .+)', 'deny_delete_tag': True, 'file_name_regex': '', 'max_file_size': 5, 'member_check': False, 'prevent_secrets': True}

  | 2020-02-25 14:13:34.378 | - | - | app-1582639980-gjzfc | +++ Error while processing 'CUT/-CUT-semantic-release'

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | File "/gitlabform/gitlabform/gitlabform/core.py", line 251, in process_all

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | self._make_requests_to_api("projects/%s/push_rule", pid, 'PUT', push_rules)

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | Setting project_settings

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | File "/gitlabform/gitlabform/gitlab/core.py", line 92, in _make_requests_to_api

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | File "/gitlabform/gitlabform/gitlabform/core.py", line 279, in process_project_push_rules

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | Traceback (most recent call last):

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | File "/gitlabform/gitlabform/gitlab/projects.py", line 105, in put_project_push_rules

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | response = self._make_request_to_api(path_as_format_string, args, method, data, expected_codes, json)

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | File "/gitlabform/gitlabform/gitlab/core.py", line 125, in _make_request_to_api

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | * [5/165] Processing: beholder/deployment-repository-forks/andover

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | self.gl.put_project_push_rules(project_and_group, push_rules)

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | File "/gitlabform/gitlabform/gitlabform/core.py", line 33, in method_wrapper

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | return method(self, project_and_group, configuration)

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | self.process_project_push_rules(project_and_group, configuration)

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | raise NotFoundException("Resource path='%s' not found!" % url)

  | 2020-02-25 14:13:34.379 | - | - | app-1582639980-gjzfc | gitlabform.gitlab.core.NotFoundException: Resource path='https://CUT/api/v4/projects/22026/push_rule' not found!


```

not sure why this occurs and how to debug it

**Comment by gdubicki** [comment]
Hi!

Have you tried to use `-d` cli flag to enable debug mode to see the full requests to and responses from GitLab? Reading those may give you hints about what is happening.

I suggest limiting your run to only a single project where the run is failing as the output is very verbose in this mode.

Also note that with full requests secrets in the requests' bodies will be revealed so be careful if you are running this in a CI/CD pipeline.

**Comment by grzesuav** [comment]
Thanks, with help of colleagues I narrow down the issue : 
`PUT` method is used, if in given repository `push_rules` was never set it causes issue (probably `POST` should be used).

After I manually went on settings site and click `Save rules` button and reruning job - it stared to work on this project

**Comment by gdubicki** [comment]
I am happy that you have found a workaroung, @grzesuav !

I did review this feature code and in fact it only uses PUTs, which is wrong. Unfortunately at the time this feature was added we did not have tests and we did not use this at my day job company so we haven’t noticed that, sorry. :(

Perhaps you could write a PR with a fix to this feature?

**Comment by grzesuav** [comment]
If you briefly explain me basing on what I can decide to use put or post - would be helpful. Don't want to do it in catch - except way .

**Comment by grzesuav** [comment]
@gdubicki added support, trying to follow convention in project.

**Comment by grzesuav** [comment]
By the way - as you're building up from python 3.5 what do you think about using type hints ? It really helps with IDE and allow to use tools like https://github.com/google/pytype to do type checking.

Also I didn't noticed any test for gitlab API calls, do you consider (or your'e against) adding thing like https://github.com/getsentry/responses for testing ? Or you have some other thing in mind ?

**Comment by gdubicki** [comment]
Hey, thanks for a quick PR!

As for the type hints: sure, lets introduce them.

About tests: we do have a framework for running tests against a real GitLab instance in a Docker container. Its slower, but also checks for GitLab bugs and API changes.

Can you add push rules tests using this framework to you PR please?

**Comment by grzesuav** [comment]
Sure, which test I should look at ? https://github.com/egnyte/gitlabform/blob/master/gitlabform/gitlabform/test/test_files.py ? 

Not sure how testing against real gitlab instance should look like, could you explain a bit ?

**Comment by gdubicki** [comment]
I will prepare one of the tests as an example one, with lots of comments, including header that will explain the concepts. I’ll ping you here when it’s done. It should happen within a few days. Thanks!

**Comment by gdubicki** [comment]
In case you want to check it out on your own then that test is ok to look at and copy-paste from.

**Comment by gdubicki** [comment]
GitHub automatically closed this issue when I merged https://github.com/egnyte/gitlabform/pull/86 ..

Thanks again for the contribution @grzesuav 👍 , please reopen this in case v1.13.3 still doesn't process the Push Rules for you properly.
