### ISSUE TITLE
New protecting branches doesn't work with files

### ISSUE THREAD

**Issue by KrystianOcado** [egnyte/gitlabform#96]
Hello!

It seems that version 1.15.0 has a bug related to new proteced branches API.

When you set protection using:

```
push_access_level: 0
merge_access_level: 30
unprotect_access_level: 40
```

and you manage some files for a project using gitlabform, an exception is raised:

```
Traceback (most recent call last):
  File "/gitlabform/gitlabform/gitlabform/core.py", line 273, in process_all
    self.process_files(project_and_group, configuration)
  File "/gitlabform/gitlabform/gitlabform/core.py", line 40, in method_wrapper
    return method(self, project_and_group, configuration)
  File "/gitlabform/gitlabform/gitlabform/core.py", line 84, in method_wrapper
    return method(self, project_and_group, SafeDict(configuration))
  File "/gitlabform/gitlabform/gitlabform/core.py", line 679, in process_files
    configuration['branches'][branch]['developers_can_push'],
KeyError: 'developers_can_push'
```

It seems that gitlabform is disabling protection to push files, but when it wants to restore previous settings it doesn't support new configuration introduced as part of: https://github.com/egnyte/gitlabform/issues/27

Simple example: https://gitlab.com/k.kichewko/gitlabform-protect-error/-/blob/master/config.yml

Worst part is, that it leaves branches unprotected.

**Comment by KrystianOcado** [comment]
I've added a PR that contains a fix for this problem: https://github.com/egnyte/gitlabform/pull/97
